In [1]:
import  torch

In [2]:
torch.cuda.is_available()

True

In [3]:
import numpy as np
import os

In [4]:
device ="cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [5]:
basic_tensor = torch.tensor([[1,2,3], [4,5,6]])
basic_tensor

tensor([[1, 2, 3],
        [4, 5, 6]])

In [6]:
basic_tensor.dtype

torch.int64

In [7]:
basic_tensor.device

device(type='cpu')

In [8]:
basic_tensor.shape

torch.Size([2, 3])

In [9]:
basic_tensor.requires_grad

False

In [10]:
tensor = torch.tensor([[1,2,3], [4,5,6]],
                      dtype=torch.float,
                      device=device,
                      requires_grad=True)
tensor

tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0', requires_grad=True)

In [11]:
tensor.dtype

torch.float32

In [12]:
tensor.device

device(type='cuda', index=0)

In [13]:
tensor.requires_grad

True

## Other commonly used tensors

In [14]:
x= torch.empty(size=(3,3))
x

tensor([[1.4585e-19, 1.1703e-19, 1.3563e-19],
        [1.5637e-01, 4.1022e+04, 6.2260e+16],
        [2.2103e+32, 7.1430e+31, 9.1371e-10]])

In [15]:
x = torch.zeros(size=(3,3))
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [16]:
x = torch.ones(size=(3,3))
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [17]:
x = torch.rand(size=(3,3))
x

tensor([[0.1305, 0.1089, 0.9339],
        [0.7072, 0.0024, 0.7048],
        [0.0107, 0.5083, 0.2002]])

In [19]:
x = torch.eye(3)
x

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [23]:
x =torch.arange(start=0, end=7, step=2.99)
x

tensor([0.0000, 2.9900, 5.9800])

In [28]:
x = torch.linspace(start=0, end=7, steps=10)
x

tensor([0.0000, 0.7778, 1.5556, 2.3333, 3.1111, 3.8889, 4.6667, 5.4444, 6.2222,
        7.0000])

In [29]:
x = torch.rand(size=(3,4)).normal_(mean=0, std=1)
x

tensor([[ 0.6191, -0.3518,  0.0301, -0.1909],
        [-0.5346,  0.1520, -0.1763,  0.7931],
        [ 1.7171, -0.3807, -0.1542, -1.3193]])

In [31]:
x = torch.rand(size=(3,4)).uniform_(3,6)
x

tensor([[3.6785, 4.1373, 4.6715, 4.4567],
        [3.0625, 4.8434, 3.7539, 5.0393],
        [5.0844, 3.0088, 5.9084, 4.7049]])

In [33]:
x= torch.diag(torch.ones(10))
x

tensor([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [34]:
x = torch.diag(5*torch.ones(10))
x

tensor([[5., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 5., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 5., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 5., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 5., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 5., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 5., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 5., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 5., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 5.]])

In [35]:
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

In [36]:
x.bool()

tensor([False,  True,  True,  True])

In [37]:
x.int()

tensor([0, 1, 2, 3], dtype=torch.int32)

In [38]:
x.short() #  int16

tensor([0, 1, 2, 3], dtype=torch.int16)

In [39]:
x.long() # int 64

tensor([0, 1, 2, 3])

In [40]:
x.half() # float 16

tensor([0., 1., 2., 3.], dtype=torch.float16)

In [41]:
x.float() # float32

tensor([0., 1., 2., 3.])

In [42]:
x.double() # float 64

tensor([0., 1., 2., 3.], dtype=torch.float64)

In [43]:
np_array =np.array([[1,2,3], [1,2,3]])
np_array

array([[1, 2, 3],
       [1, 2, 3]])

In [45]:
tensor = torch.from_numpy(np_array)
tensor

tensor([[1, 2, 3],
        [1, 2, 3]])

In [46]:
tensor.numpy()

array([[1, 2, 3],
       [1, 2, 3]])