In [2]:
import numpy as np
import torch
import os

In [3]:
x = torch.arange(start=10, end=20, step=4)
y = torch.arange(start=5, end=15, step=4)

x.shape, y.shape

(torch.Size([3]), torch.Size([3]))

In [4]:
x

tensor([10, 14, 18])

In [5]:
y

tensor([ 5,  9, 13])

In [6]:
x+y

tensor([15, 23, 31])

In [7]:
torch.dot(x,y)

tensor(410)

In [8]:
x-y

tensor([5, 5, 5])

In [9]:
x*y # Element wise multiplication

tensor([ 50, 126, 234])

In [10]:
x/y # Element wise division

tensor([2.0000, 1.5556, 1.3846])

In [11]:
z = torch.ones(3)
z

tensor([1., 1., 1.])

In [12]:
z = z + x
z

tensor([11., 15., 19.])

In [13]:
z.add_(x) # Inplace addition

tensor([21., 29., 37.])

In [14]:
x.pow(2)

tensor([100, 196, 324])

In [15]:
x**2

tensor([100, 196, 324])

In [16]:
x > 0

tensor([True, True, True])

In [17]:
A = torch.rand(size=(3,5))
B = torch.rand(size=(5,3))

In [18]:
A @ B # Matrix multiplication

tensor([[1.8091, 2.6483, 1.2956],
        [0.8293, 0.9534, 0.3630],
        [0.9787, 1.1143, 0.4294]])

In [19]:
A.matmul(B)

tensor([[1.8091, 2.6483, 1.2956],
        [0.8293, 0.9534, 0.3630],
        [0.9787, 1.1143, 0.4294]])

In [20]:
X = torch.rand(size=(3,3))
X.matrix_exp()

tensor([[2.0856, 0.2164, 0.1678],
        [1.8593, 1.6871, 0.7908],
        [1.1871, 0.3784, 1.2000]])

In [21]:
X.matrix_power(2)

tensor([[0.5891, 0.1393, 0.1197],
        [1.3110, 0.3953, 0.3293],
        [0.6996, 0.1887, 0.1894]])

## Broadcasting

In [22]:
A

tensor([[0.8800, 0.9709, 0.3837, 0.4730, 0.8811],
        [0.2091, 0.1122, 0.7635, 0.0649, 0.1577],
        [0.0110, 0.3566, 0.5238, 0.3030, 0.4401]])

In [23]:
A + 1

tensor([[1.8800, 1.9709, 1.3837, 1.4730, 1.8811],
        [1.2091, 1.1122, 1.7635, 1.0649, 1.1577],
        [1.0110, 1.3566, 1.5238, 1.3030, 1.4401]])

In [24]:
A - 1

tensor([[-0.1200, -0.0291, -0.6163, -0.5270, -0.1189],
        [-0.7909, -0.8878, -0.2365, -0.9351, -0.8423],
        [-0.9890, -0.6434, -0.4762, -0.6970, -0.5599]])

In [25]:
A * 5

tensor([[4.3999, 4.8543, 1.9186, 2.3652, 4.4054],
        [1.0455, 0.5611, 3.8176, 0.3244, 0.7887],
        [0.0551, 1.7829, 2.6188, 1.5150, 2.2003]])

In [26]:
A.shape

torch.Size([3, 5])

In [27]:
C = torch.ones((1,5))

In [28]:
A - C

tensor([[-0.1200, -0.0291, -0.6163, -0.5270, -0.1189],
        [-0.7909, -0.8878, -0.2365, -0.9351, -0.8423],
        [-0.9890, -0.6434, -0.4762, -0.6970, -0.5599]])

In [29]:
D = torch.ones((3,1))
D

tensor([[1.],
        [1.],
        [1.]])

In [30]:
A - D

tensor([[-0.1200, -0.0291, -0.6163, -0.5270, -0.1189],
        [-0.7909, -0.8878, -0.2365, -0.9351, -0.8423],
        [-0.9890, -0.6434, -0.4762, -0.6970, -0.5599]])

In [31]:
A + D

tensor([[1.8800, 1.9709, 1.3837, 1.4730, 1.8811],
        [1.2091, 1.1122, 1.7635, 1.0649, 1.1577],
        [1.0110, 1.3566, 1.5238, 1.3030, 1.4401]])

In [32]:
torch.sum(D)

tensor(3.)

In [33]:
torch.sum(A)

tensor(6.5306)

In [34]:
torch.min(A)

tensor(0.0110)

In [35]:
torch.max(A)

tensor(0.9709)

In [36]:
torch.min(A, dim=1)

torch.return_types.min(
values=tensor([0.3837, 0.0649, 0.0110]),
indices=tensor([2, 3, 0]))

In [37]:
A

tensor([[0.8800, 0.9709, 0.3837, 0.4730, 0.8811],
        [0.2091, 0.1122, 0.7635, 0.0649, 0.1577],
        [0.0110, 0.3566, 0.5238, 0.3030, 0.4401]])

In [38]:
torch.max(A, dim=0)

torch.return_types.max(
values=tensor([0.8800, 0.9709, 0.7635, 0.4730, 0.8811]),
indices=tensor([0, 0, 1, 0, 0]))

In [40]:
torch.abs(-A)

tensor([[0.8800, 0.9709, 0.3837, 0.4730, 0.8811],
        [0.2091, 0.1122, 0.7635, 0.0649, 0.1577],
        [0.0110, 0.3566, 0.5238, 0.3030, 0.4401]])

In [41]:
torch.argmax(A)

tensor(1)

In [42]:
torch.argmin(A)

tensor(10)

In [43]:
torch.mean(A)

tensor(0.4354)

In [45]:
torch.argmax(A, dim=1) # Row wise

tensor([1, 2, 2])

In [47]:
torch.argmin(A, dim=0) # Column wise

tensor([2, 1, 0, 1, 1])

In [49]:
D = torch.ones(A.shape)
D

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [51]:
torch.eq(A, D)

tensor([[False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False]])

In [52]:
torch.eq(D, D)

tensor([[True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True]])

In [53]:
torch.sort(A)

torch.return_types.sort(
values=tensor([[0.3837, 0.4730, 0.8800, 0.8811, 0.9709],
        [0.0649, 0.1122, 0.1577, 0.2091, 0.7635],
        [0.0110, 0.3030, 0.3566, 0.4401, 0.5238]]),
indices=tensor([[2, 3, 0, 4, 1],
        [3, 1, 4, 0, 2],
        [0, 3, 1, 4, 2]]))

In [55]:
torch.clamp(A, min=0.5)

tensor([[0.8800, 0.9709, 0.5000, 0.5000, 0.8811],
        [0.5000, 0.5000, 0.7635, 0.5000, 0.5000],
        [0.5000, 0.5000, 0.5238, 0.5000, 0.5000]])