In [1]:
import torch
import numpy as np
import os

## Indexing, Slicing

In [2]:
x = torch.rand(size=(3,4))
x

tensor([[0.5626, 0.6212, 0.6844, 0.0706],
        [0.8288, 0.2293, 0.9136, 0.6512],
        [0.3604, 0.8173, 0.6542, 0.0145]])

x[row, cols]

row -> start: stop: step

col -> start: stop: step

In [3]:
x[0,:]

tensor([0.5626, 0.6212, 0.6844, 0.0706])

In [5]:
x[:, 0]

tensor([0.5626, 0.8288, 0.3604])

In [6]:
x[0:2, 0:3]

tensor([[0.5626, 0.6212, 0.6844],
        [0.8288, 0.2293, 0.9136]])

In [7]:
x[0,0]

tensor(0.5626)

In [8]:
x[0,0] = 111
x

tensor([[1.1100e+02, 6.2116e-01, 6.8442e-01, 7.0623e-02],
        [8.2885e-01, 2.2929e-01, 9.1357e-01, 6.5118e-01],
        [3.6038e-01, 8.1728e-01, 6.5417e-01, 1.4534e-02]])

In [9]:
x[0,0]

tensor(111.)

## Conactenation

In [10]:
x = torch.rand(size=(3,4))
y = torch.rand(size=(3,4))

In [13]:
x

tensor([[0.7474, 0.0556, 0.3143, 0.6278],
        [0.8801, 0.7006, 0.1106, 0.4661],
        [0.9098, 0.2809, 0.0540, 0.3663]])

In [14]:
y

tensor([[0.7842, 0.4631, 0.8390, 0.1961],
        [0.2171, 0.3180, 0.4815, 0.4985],
        [0.4128, 0.6630, 0.5031, 0.7337]])

In [12]:
torch.cat((x,y), dim=0)

tensor([[0.7474, 0.0556, 0.3143, 0.6278],
        [0.8801, 0.7006, 0.1106, 0.4661],
        [0.9098, 0.2809, 0.0540, 0.3663],
        [0.7842, 0.4631, 0.8390, 0.1961],
        [0.2171, 0.3180, 0.4815, 0.4985],
        [0.4128, 0.6630, 0.5031, 0.7337]])

## Reshaping

In [15]:
x.shape

torch.Size([3, 4])

In [19]:
x.reshape(6,2)

tensor([[0.7474, 0.0556],
        [0.3143, 0.6278],
        [0.8801, 0.7006],
        [0.1106, 0.4661],
        [0.9098, 0.2809],
        [0.0540, 0.3663]])

In [21]:
x.reshape(1, 12)

tensor([[0.7474, 0.0556, 0.3143, 0.6278, 0.8801, 0.7006, 0.1106, 0.4661, 0.9098,
         0.2809, 0.0540, 0.3663]])

In [23]:
x.view(-1) # flattening

tensor([0.7474, 0.0556, 0.3143, 0.6278, 0.8801, 0.7006, 0.1106, 0.4661, 0.9098,
        0.2809, 0.0540, 0.3663])

In [25]:
x.view(-1).shape

torch.Size([12])

In [27]:
# batch flattening ops
batch = 16

torch.rand((batch, 2, 5)).view(batch, -1)

tensor([[0.5519, 0.5072, 0.3915, 0.6353, 0.5891, 0.8015, 0.7716, 0.5418, 0.8063,
         0.9357],
        [0.2561, 0.3749, 0.0283, 0.0417, 0.8921, 0.5721, 0.8903, 0.6978, 0.3615,
         0.6857],
        [0.8786, 0.2690, 0.3884, 0.6140, 0.3517, 0.4823, 0.3891, 0.0734, 0.9154,
         0.8408],
        [0.9976, 0.5460, 0.3669, 0.3330, 0.0733, 0.6535, 0.9381, 0.7691, 0.0991,
         0.7651],
        [0.4708, 0.4084, 0.6457, 0.1650, 0.2047, 0.7875, 0.3542, 0.8034, 0.5618,
         0.2932],
        [0.1343, 0.6667, 0.7612, 0.0140, 0.1975, 0.1909, 0.4452, 0.9187, 0.1427,
         0.5303],
        [0.1862, 0.2923, 0.9850, 0.5702, 0.7046, 0.2907, 0.4485, 0.7850, 0.2830,
         0.0731],
        [0.6387, 0.0529, 0.3986, 0.7146, 0.5349, 0.4256, 0.1217, 0.0826, 0.6806,
         0.3960],
        [0.7234, 0.5658, 0.8241, 0.5114, 0.4304, 0.4998, 0.0153, 0.2537, 0.4721,
         0.4446],
        [0.1060, 0.2320, 0.6453, 0.0782, 0.1108, 0.1379, 0.2729, 0.9950, 0.0252,
         0.7838],
        [0